### ISSUE TITLE
com.zhicall.care 这个包缺少

### ISSUE THREAD

**Issue by zeng531196248** [hoboloser/IM#1]
博主你好，下载了你写的项目看了，但是缺少了这个包，能传下源码包吗？感谢！

**Comment by hoboloser** [comment]
[maven依赖中缺少的jar包.zip](https://github.com/hoboloser/IM/files/1210150/maven.jar.zip)

不好意思，忘了这个版本库里面没有了。另附上缺少的jar

**Comment by zeng531196248** [comment]
好的,谢谢，最好是附上源代码，
