### ISSUE TITLE
你好还是缺少一些文件！

### ISSUE THREAD

**Issue by zeng531196248** [hoboloser/IM#2]
我的QQ531196248 ，博主可以加下吗，学习下您写的工程。
在启动时候出现		缺少		<value>file:${ZHICALL_CONFIG}/socket/socket.properties</value>

**Comment by hoboloser** [comment]
[socket.zip](https://github.com/hoboloser/IM/files/1210504/socket.zip)
 这个是配置文件，通过环境变量配置的，可以自行配置

**Comment by hoboloser** [comment]
你的QQ设置了验证问题，加不了。不过你可以加我QQ 731638471
